= Hawkular Accounts

Hawkular Accounts is the user/organization module for Hawkular projects. It provides the registration feature,
setting up of organizations and related features. The main registration and user login is provided by
[http://keycloak.jboss.org/]Keycloak, while organizations and permissions are implemented in Hawkular Accounts itself.

Hawkular is a monitoring suite, that consists of several sub-projects for
storing of metrics, alerting on incoming events and more. Those projects are developed
in their own GitHub repositories.

ifdef::env-github[]
[link=https://travis-ci.org/hawkular/hawkular-accounts]
image:https://travis-ci.org/hawkular/hawkular-accounts.svg["Build Status", link="https://travis-ci.org/hawkular/hawkular-accounts"]
endif::[]

== About Accounts

The project is divided into several modules. More information about the individual modules can be found in the
respective module's README files.

* accounts: the REST backend, handling the actions from the Hawkular Accounts UI.
* api: the components that are intended to be consumed by other Hawkular components.
* distribution: assembles a complete Wildfly with Keycloak and Hawkular Accounts, suitable for isolated
  development/testing.
* sample: a sample on how to integrate Accounts into other Hawkular projects.

The hawt.io UI for Hawkular Accounts is located in the hawkular-ui-components project.

== Basic usage

First, add the API as a dependency:
[source,xml]
----
<dependency>
  <groupId>org.hawkular.accounts</groupId>
  <artifactId>hawkular-accounts-api</artifactId>
  <version>${project.version}</version>
</dependency>
----

With that, you can now inject the permission checker and other parts of the API directly into your EJBs and other
managed beans.

Hawkular Accounts is based on the following concepts:

* *Resource* - something that you want to protect; it might be an Alert, an Inventory item, a Metric, ...
* *Persona* - either a User or an Organization. A real User can be impersonating an Organization, so, this Organization
  would be the current Persona. In most cases, the current Persona corresponds to an intuitive notion of the
  "current user" or "current tenant".
* *User* - a real user of the application. In most cases, consumers of Hawkular Accounts do not need to deal directly
  with users.
* *Organization* - a non-user which has an Owner and a set of Members. In most cases, consumers of Hawkular Accounts
  do not need to deal directly with organizations.
* *Owner* - owns a Resource, and can be (currently) either a Hawkular User or an Organization.
* *Member* - a User or Organization that can be part of an Organization.

To retrieve the current Persona:
[source,java]
----
@Stateless
class FooService {
    @Inject
    Persona persona;
}
----

In order to check if a Persona has access to a given Resource, a record of this resource should exist in Hawkular
Accounts. For instance, if you need to protect a metric, you need to:

* Create a Resource with a unique key (possibly the same ID you have in your persistent storage), specifying the
  Owner (usually, the current Persona).
* Later on, you can check if the current Persona (or whichever Persona relevant to you) has access to the resource, via
  `PermissionChecker`.

Example:
[source,java]
----
@Stateless
class FooService {
    @Inject
    Persona persona;

    @Inject
    PermissionChecker permissionChecker;

    @Inject
    ResourceService resourceService;

    @Inject
    @NamedOperation("foo-read")
    Operation operationRead;

    public void createFoo() {
        Foo foo = new Foo(id); // this is your business resource

        // the ID can be anything that is unique. When omitted, a new UUID is created and you'll be responsible for
        // storing it somewhere and informing it next time you need access to this resource. Also, we need to
        // explicitly know who is the owner.
        resourceService.create(foo.getId(), persona);

        // your storage might be Cassandra, JPA-based storage, in memory map, ...
        storage.persist(foo);
    }

    public Foo getFoo(String id) {
        Foo foo = storage.getFoo(id); // this is your business resource

        // when omitted, the user is assumed to be the current user on the permission checker
        if (permissionChecker.isAllowedTo(operationRead, foo.getId())) {
            // return it to the user
        } else {
            // return a forbidden message
        }
    }
}
----

Note that Hawkular Accounts depend on Keycloak. Therefore, make sure to either run it inside Kettle or configure a
Keycloak instance appropriately.

== Operations and Roles

As a one-time setup, the permission set needs to be configured. With that, a list of operations needs to be provided,
as well as which roles are allowed to perform those operations. To facilitate this procedure, the `OrganizationService`
can be used as a `@Singleton @Startup` EJB, with the setup on a `@PostConstruct` method. For example:

[source,java]
----
operationService
        .setup("organization-create")
        .add("Monitor") // means: all roles
        .commit()

        .setup("organization-read")
        .add("Maintainer")
        .commit()

        .setup("organization-delete")
        .add("SuperUser")
        .commit()

        .setup("organization-update")
        .add("Maintainer")
        .commit();
----

Hawkular Accounts ships with the same roles as Wildfly and with the same rules (ie: SuperUser will be given permission
to perform operations marked as allowed for "user with at least Monitor role"). So, adding the role "Monitor" during
the setup will automatically add all other roles to it.

Note as well that if the set of roles for a given operation has not changed from what we currently have in the
database, nothing is performed.

More about the Wildfly roles can be found in this
link:http://blog.arungupta.me/role-based-access-control-wildfly-8/[blog post]

== How to build Hawkular Accounts from source

The API and backend can be build as a regular Maven project:
[source,bash]
----
$ mvn clean install
----

To build a distribution with Wildfly and Keycloak, use:
[source,bash]
----
$ mvn clean install -Pdistribution
----

To build all modules, including sample and distribution, use:
[source,bash]
----
$ mvn clean install -Pdistribution,sample
----

Note that none of those currently ships with the UI. Follow the instructions on
link:https://github.com/hawkular/hawkular-ui-components[hawkular-ui-components] in order to run the UI.

== License

Hawkular Accounts is released under Apache License, Version 2.0 as described in the link:LICENSE[LICENSE] document

----
   Copyright 2015 Red Hat, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
----




