= Hawkular Accounts

Hawkular Accounts is the user/organization module for Hawkular projects. It provides the registration feature,
setting up of organizations and related features. The main registration and user login is provided by Keycloak, while
organizations and permissions are handled by ourselves.

Hawkular is a modular systems monitoring suite, that consists of several sub-projects for
storing of metrics, alerting on incoming events and more. Those projects are developed
in their own GitHub repositories.

ifdef::env-github[]
[link=https://travis-ci.org/hawkular/hawkular-accounts]
image:https://travis-ci.org/hawkular/hawkular-accounts.svg["Build Status", link="https://travis-ci.org/hawkular/hawkular-accounts"]
endif::[]

== About Accounts

The project is divided into several modules. More information about the individual modules can be found on the
module's README files.

* accounts: the REST backend, handling the actions from the Hawkular Accounts UI.
* api: the components that are supposed to be consumed by other Hawkular components.
* distribution: assembles a complete Wildfly with Keycloak and Hawkular Accounts, suitable for isolated
development/testing.
* sample: a sample on how to integrate Accounts into other Hawkular projects.

The hawt.io UI for Hawkular Accounts is located in the hawkular-ui-components project.

== Setup

The API and backend can be build as a regular Maven project:
[source,bash]
----
$ mvn clean install
----

To build a distribution with Wildfly and Keycloak, use:
[source,bash]
----
$ mvn clean install -Pdistribution
----

To build all modules, including sample and distribution, use:
[source,bash]
----
$ mvn clean install -Pdistribution,sample
----

Note that none of those currently ships with the UI. Follow the instructions on
link:https://github.com/hawkular/hawkular-ui-components[hawkular-ui-components] in order to run the UI.

== License

Hawkular Accounts is released under Apache License, Version 2.0 as described in the link:LICENSE[LICENSE] document

----
   Copyright 2015 Red Hat, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
----




