= Hawkular Accounts - Distribution

This module builds a complete distribution of Hawkular Accounts, meaning, it assembles a Wildfly with Keycloak and
deploys the backend to it. No further configuration is required.

Note, however, that this module will probably be replaced by a proper build of the whole Hawkular. This module is
here only as a helper in testing/integrating other modules with Hawkular Accounts.

Hawkular is a modular systems monitoring suite, that consists of several sub-projects for
storing of metrics, alerting on incoming events and more. Those projects are developed
in their own GitHub repositories.

ifdef::env-github[]
[link=https://travis-ci.org/hawkular/hawkular-accounts]
image:https://travis-ci.org/hawkular/hawkular-accounts.svg["Build Status", link="https://travis-ci
.org/hawkular/hawkular-accounts"]
endif::[]

== About the distribution

This distribution takes the Keycloak Appliance and builds on top of it. It applies some XSLT transformations to the
standalone.xml . Besides, the build generates UUIDs used for the application secrets.

== Setup

From the parent module:
[source,bash]
----
$ mvn clean install -Pdistribution
----

This will generate a Wildfly bundle with all the requirements on the distribution/target directory.

== License

Hawkular-Accounts is released under Apache License, Version 2.0 as described in the link:LICENSE[LICENSE] document

----
   Copyright 2015 Red Hat, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
----




