= Hawkular Accounts - Sample

This is a backend sample, aimed to be used as reference for components that want to integrate with Hawkular Accounts.

== About this sample

This sample is a very basic backend that persist a "Sample" resource into the database.
The hawt.io UI for this sample is located in the hawkular-ui-components project.

== Setup

After building the main distribution (see the parent module's README), build this sample by running:
[source,bash]
----
$ mvn clean install
----

You can also build all components from the parent, by using this command:
[source,bash]
----
$ mvn clean install -Pdistribution,sample
----

The sample WAR file is not deployed by default. Just copy the generated WAR file as "hawkular-accounts-sample.war" into
Wildfly's deployment directory from the "distribution" module.

Note that for your own component, you'll have to adapt the standalone.xsl to include your deployment under the
"secure-deployments" section.

To test the sample, you can perform the following curl call:

[source,bash]
---
$ curl -u jdoe:password -H "Accept: application/json" -H "Content-Type: application/json" -X POST -d '{"name":"test"}'
http://localhost:8080/hawkular-accounts-sample/samples
---

== License

Hawkular-Accounts is released under Apache License, Version 2.0 as described in the link:LICENSE[LICENSE] document

----
   Copyright 2015 Red Hat, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
----




