= Hawkular Accounts - API

This is the API and EJB module for Hawkular Accounts. The EJBs can be injected into other managed beans (including
other EJBs) by using CDI's `@Inject`.

== About the API

This API can be freely used by other Hawkular projects for checking the authorization to resources. As much as
possible, it provides a stable API for authorization and changes should be backwards compatible. Packages marked
as `internal`, however, should not be used and can be changed without deprecation notices. Make sure to look at the
test suite, which also serves as part of the documentation for the API usage.

== Setup

The API can be build as a regular Maven project:
[source,bash]
----
$ mvn clean install
----

To use the API in your project, add the following Maven dependency:
[source,xml]
----
<dependency>
  <groupId>org.hawkular.accounts</groupId>
  <artifactId>hawkular-accounts-api</artifactId>
  <version>${project.version}</version>
</dependency>
----

Please, refer to the JavaDocs to learn the appropriate usage of the API.

== License

Hawkular Accounts is released under Apache License, Version 2.0 as described in the link:LICENSE[LICENSE] document

----
   Copyright 2015 Red Hat, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
----




